---
name: ${PROJECT_NAME}
networks:
  default:
    name: ${HOST_GROUP_NAME}
    # external: true # If network already exists, use this and comment out rest
    # For specific subnets, use or modify the configuration below
    driver: bridge
    attachable: true
    # internal: true # OPTIONAL: If Internet access is unneeded for this network
    # enable_ipv6: true # OPTIONAL: affects IPv6 subnet line below
    ipam:
      config:
        - subnet: ${DOCKER_NETWORK_IPV4_CIDR}
          gateway: ${DOCKER_NETWORK_IPV4_GATEWAY}
        # - subnet: fe80:db8::/64 # OPTIONAL: requires `enable_ipv6: true`

include:
  # # Include service files listed in ${HOST_COMPOSE_FOLDER} below to launch 
  # # them when Docker becomes available on startup, using the same pattern as 
  # # in the example below. If a service does not require an env_file, simply 
  # # leave that line out.
  # - path:     ${HOST_COMPOSE_FOLDER}/servicename.yml
  #   env_file: ${HOST_COMPOSE_FOLDER}/servicename.env

  - path:     ${HOST_COMPOSE_FOLDER}/docker-socket-proxy.yml
  - path:     ${HOST_COMPOSE_FOLDER}/traefik.yml
    env_file: ${HOST_COMPOSE_FOLDER}/traefik.env
