secrets:
  DO_AUTH_TOKEN:
    # Since we're using DigitalOcean's DNS to verify the Let's Encrypt 
    # certificates for the local network, we need a DO API token (available at 
    # https://cloud.digitalocean.com/account/api/tokens ), which is stored in 
    # the special "secrets" mount (such as a LUKS volume).
    file: "${HOST_DATA_FOLDER}/secrets/${TRAEFIK_ACME_TOKEN_FILE}"
services:
  traefik:
    image: traefik:3
    container_name: traefik
    secrets:
      - DO_AUTH_TOKEN
    environment:
      DO_AUTH_TOKEN_FILE: /run/secrets/DO_AUTH_TOKEN
    expose:
      - 8080
    ports:
      - ${HOST_IPV4_LOCAL}:80:80       # HTTP  (LAN)
      - ${HOST_IPV4_LOCAL}:443:443     # HTTPS (LAN)
      - ${HOST_IPV4_LOCAL}:${TRAEFIK_DASHBOARD_PORT}:8080   # Dashboard
    volumes:
      - ${HOST_DATA_FOLDER}/secrets/traefik-certificates.json:/etc/traefik/certs/acme.json:rw # for Let's Encrypt certificates
      - ${HOST_DATA_FOLDER}/apps/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro # Traefik configuration file
      - ${HOST_DATA_FOLDER}/apps/traefik/logs:/var/log/traefik:rw # logs
      - ${HOST_DATA_FOLDER}/apps/traefik/sites:/etc/traefik/sites:rw # for File provider
      - /var/run/docker.sock:/var/run/docker.sock:ro # for Docker provider
    labels:
      io.containers.autoupdate: registry
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
      restart_policy:
        condition: on-failure
        max_attempts: 10
